apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Release.Name }}
      datasource:
        url: jdbc:{{ .Values.database.type }}://{{ .Values.database.address }}/ecommerce?createDatabaseIfNotExist=true
        username: {{ .Values.database.username }}
        password: {{ .Values.database.password }}
        driver-class-name: org.mariadb.jdbc.Driver

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
        open-in-view: false

      security:
        user:
          name: berna
          password: berna

    server:
      port: {{ .Values.service.port }}
    management:
    endpoint:
      health:
        probes:
          enabled: true
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true

