spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://192.168.1.51:30036/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: 12345Wq!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  security:
    user:
      name: berna
      password: berna

server:
  port: 8084
management:
  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true



