spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  security:
    user:
      name: berna
      password: berna

server:
  port: 8084
